#!/usr/bin/env python3
"""Build combined Typst source files for protocol collections.

Reads individual protocol .typ files, extracts metadata and content,
generates combined .typ sources with shared preamble, continuous page
numbering, and state-based dynamic headers/footers.

Usage:
    python scripts/build-combined.py          # generate .typ sources
    python scripts/build-combined.py --compile # also compile to PDF
"""

import re
import subprocess
import sys
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
ADULT_DIR = PROJECT / "output/flowcharts/adult/typst"
CHILD_DIR = PROJECT / "output/flowcharts/child/typst"
COMBINED_DIR = PROJECT / "output/flowcharts/combined"


def extract_metadata(text: str) -> dict:
    """Extract #let variable assignments from a .typ file."""
    meta = {}
    for m in re.finditer(r'#let\s+([\w-]+)\s*=\s*"([^"]*)"', text):
        key = m.group(1).replace("-", "_")
        meta[key] = m.group(2)
    return meta


def extract_content(text: str) -> str:
    """Extract protocol content (diagrams + reference notes), stripping preamble."""
    lines = text.split("\n")

    # Find content start: first separator block followed by PAGE comment
    content_start = None
    for i in range(len(lines) - 1):
        if re.match(r"^// =+$", lines[i].strip()) and "PAGE" in lines[i + 1]:
            content_start = i
            break

    if content_start is None:
        # Fallback: first #diagram(
        for i, line in enumerate(lines):
            if line.strip().startswith("#diagram("):
                content_start = i
                break

    if content_start is None:
        return ""

    content = "\n".join(lines[content_start:])

    # Fix icon paths: individual files are 4 levels deep, combined is 3 levels deep
    content = content.replace("../../../../icons/", "../../../icons/")

    # Remove any standalone #pagebreak() at the very start (we add our own)
    content = re.sub(r"^\s*#pagebreak\(\)\s*\n?", "", content)

    return content


PREAMBLE = r"""// Combined Protocol Flowcharts
// Auto-generated by scripts/build-combined.py
// Do not edit manually — regenerate from individual protocol sources.

#import "@preview/fletcher:0.5.7": diagram, node, edge

// === STATE (tracks current protocol for dynamic header/footer) ===
#let current-protocol = state("protocol", (
  id: "",
  subject: "",
  scenario: "",
  sop: "",
  age: "",
  version: "",
  source: "",
  generation_date: "",
))

// === COLOURS ===
#let clr-step = rgb("#f0f9ff")
#let clr-step-stroke = rgb("#3b82f6")
#let clr-decision = rgb("#eff6ff")
#let clr-decision-stroke = rgb("#2563eb")
#let clr-yes = rgb("#16a34a")
#let clr-yes-fill = rgb("#f0fdf4")
#let clr-no = rgb("#dc2626")
#let clr-no-fill = rgb("#fef2f2")
#let clr-warning = rgb("#dc2626")
#let clr-warning-fill = rgb("#fef2f2")
#let clr-equip = rgb("#92400e")
#let clr-equip-fill = rgb("#fefce8")
#let clr-terminal = rgb("#1e3a5f")
#let clr-rejoin = rgb("#b0b8c4")

#let clr-age-adult = rgb("#ea580c")
#let clr-age-child = rgb("#0d9488")
#let clr-condition = rgb("#1e40af")
#let clr-scenario = rgb("#4b5563")

#let clr-page-bg = rgb("#1e293b")
#let clr-page-fg = white
#let clr-header-bg = rgb("#f8f9fb")
#let clr-header-border = rgb("#e2e5ea")

// === ICON PATHS ===
#let mda-logo = "../../../icons/mda/mda.png"

// === ICONS ===
#let icon-bandage = text(size: 12pt)[#emoji.hospital]
#let icon-blanket = text(size: 12pt)[#emoji.coat]
#let icon-brain = text(size: 12pt)[#emoji.brain]
#let icon-breath = text(size: 12pt)[#emoji.wind]
#let icon-calm = text(size: 12pt)[#emoji.hands.open]
#let icon-camera = text(size: 12pt)[#emoji.camera]
#let icon-clock = text(size: 12pt)[#emoji.clock]
#let icon-cold = text(size: 12pt)[#emoji.snowflake]
#let icon-cool = text(size: 12pt)[#emoji.snowflake]
#let icon-drop = text(size: 12pt)[#emoji.drops]
#let icon-fire = text(size: 12pt)[#emoji.fire]
#let icon-food = text(size: 12pt)[#emoji.bread]
#let icon-glove = text(size: 12pt)[#emoji.hand]
#let icon-heart = text(size: 12pt)[#emoji.heart]
#let icon-med = text(size: 12pt)[#emoji.pill]
#let icon-monitor = text(size: 12pt)[#emoji.eye]
#let icon-person = text(size: 12pt)[#emoji.person]
#let icon-phone = text(size: 12pt)[#emoji.phone]
#let icon-press = text(size: 12pt)[#emoji.hand]
#let icon-search = text(size: 12pt)[#emoji.magnify.l]
#let icon-shield = text(size: 12pt)[#emoji.shield]
#let icon-sit = text(size: 12pt)[#emoji.person]
#let icon-snake = text(size: 12pt)[#emoji.snake]
#let icon-spider = text(size: 12pt)[#emoji.spider]
#let icon-syringe = text(size: 12pt)[#emoji.syringe]
#let icon-temp = text(size: 12pt)[#emoji.thermometer]
#let icon-thermo = text(size: 12pt)[#emoji.thermometer]
#let icon-thermometer = text(size: 12pt)[#emoji.thermometer]
#let icon-warm = text(size: 12pt)[#emoji.fire]
#let icon-warn = text(size: 12pt)[#emoji.warning]
#let icon-warning = text(size: 12pt)[#emoji.warning]
#let icon-water = text(size: 12pt)[#emoji.drops]
#let icon-zap = text(size: 12pt)[#emoji.lightning]

// === PAGE SETUP ===
#set page(
  paper: "a4",
  margin: (top: 2.8cm, bottom: 2cm, left: 1.5cm, right: 1.5cm),
  header: context {
    let p = current-protocol.get()
    let age-clr = if p.age == "CHILD" { clr-age-child } else { clr-age-adult }
    let page-num = counter(page).get().first()
    let page-total = counter(page).final().first()
    rect(fill: age-clr, width: 100%, height: 3pt, radius: (top: 2pt, bottom: 0pt))[]
    rect(fill: clr-header-bg, width: 100%, inset: (x: 10pt, y: 6pt), stroke: (bottom: 1pt + clr-header-border))[
      #grid(
        columns: (60pt, 1fr, 60pt),
        gutter: 0pt,
        [],
        align(center)[
          #text(size: 15pt, weight: "bold", fill: age-clr, tracking: 0.5pt)[#upper(p.age)]
          #h(5pt)
          #text(size: 11pt, fill: rgb("#94a3b8"))[#sym.triangle.stroked.r]
          #h(5pt)
          #text(size: 15pt, weight: "bold", fill: clr-condition, tracking: 0.5pt)[#upper(p.subject)]
          #h(5pt)
          #text(size: 11pt, fill: rgb("#94a3b8"))[#sym.triangle.stroked.r]
          #h(5pt)
          #text(size: 15pt, weight: "bold", fill: clr-scenario, tracking: 0.5pt)[#upper(p.scenario)]
          #v(3pt)
          #text(size: 8pt, fill: rgb("#94a3b8"), tracking: 1pt)[SOP #p.sop]
        ],
        align(right + horizon)[
          #rect(fill: clr-page-bg, radius: 4pt, inset: (x: 10pt, y: 5pt))[
            #text(fill: clr-page-fg, weight: "bold", size: 14pt)[#page-num]#text(fill: rgb("#94a3b8"), weight: "bold", size: 14pt)[ \/ ]#text(fill: clr-page-fg, weight: "bold", size: 14pt)[#page-total]
          ]
        ],
      )
    ]
  },
  footer: context {
    let p = current-protocol.get()
    let page-num = counter(page).get().first()
    let page-total = counter(page).final().first()
    rect(fill: clr-header-bg, width: 100%, inset: (x: 10pt, y: 6pt), stroke: (top: 1pt + clr-header-border, bottom: 0pt), radius: (top: 0pt, bottom: 2pt))[
      #grid(
        columns: (1fr, auto, 1fr),
        gutter: 0pt,
        align(left + horizon)[
          #text(size: 7pt, fill: rgb("#94a3b8"))[
            #text(weight: "bold", fill: rgb("#64748b"))[#p.id] · v#p.version \
            #p.generation_date · #p.source
          ]
        ],
        align(center + horizon)[
          #rect(fill: rgb("#fef3c7"), radius: 3pt, inset: (x: 8pt, y: 3pt), stroke: 0.5pt + rgb("#f59e0b"))[
            #text(size: 7pt, fill: rgb("#92400e"), weight: "bold")[
              Personal reference only — not medical advice
            ]
          ]
          #v(2pt)
          #text(size: 5.5pt, fill: rgb("#94a3b8"))[
            Daniel Rosehill · share with attribution
          ]
        ],
        align(right + horizon)[
          #rect(fill: clr-page-bg, radius: 3pt, inset: (x: 8pt, y: 3pt))[
            #text(fill: clr-page-fg, weight: "bold", size: 11pt)[#page-num]#text(fill: rgb("#94a3b8"), weight: "bold", size: 11pt)[ \/ ]#text(fill: clr-page-fg, weight: "bold", size: 11pt)[#page-total]
          ]
        ],
      )
    ]
  },
)

#set text(font: ("IBM Plex Sans", "IBM Plex Sans Hebrew"), size: 10pt, dir: ltr)

// === HELPERS ===
#let action(word) = { text(weight: "bold", fill: clr-condition, size: 11pt)[#upper(word)] }

#let yes-label = rect(fill: clr-yes, radius: 10pt, inset: (x: 6pt, y: 2pt))[#text(fill: white, weight: "bold", size: 11pt)[Y]]
#let no-label = rect(fill: clr-no, radius: 10pt, inset: (x: 6pt, y: 2pt))[#text(fill: white, weight: "bold", size: 11pt)[N]]

#let keep-together(body) = { block(breakable: false)[#body] }

#let do-not-box(items) = {
  keep-together[
    #rect(fill: clr-warning-fill, stroke: 2pt + clr-warning, radius: 6pt, width: 100%, inset: 10pt)[
      #set text(size: 10pt)
      #text(fill: clr-warning, weight: "bold", size: 13pt)[DO NOT:]
      #v(4pt)
      #for item in items [
        #text(fill: clr-warning, weight: "bold")[#emoji.crossmark] #item \
      ]
    ]
  ]
}

#let equipment-box(items) = {
  keep-together[
    #rect(fill: clr-equip-fill, stroke: 1pt + rgb("#ca8a04"), radius: 6pt, width: 100%, inset: 10pt)[
      #set text(size: 10pt)
      #text(fill: clr-equip, weight: "bold", size: 11pt)[Equipment needed:]
      #v(4pt)
      #for item in items [ — #item \ ]
    ]
  ]
}

// ============================================================
// PROTOCOLS BEGIN
// ============================================================
"""


def state_update(meta: dict) -> str:
    """Generate a Typst state update block for a protocol."""
    return f"""
#pagebreak(weak: true)
#current-protocol.update((
  id: "{meta.get('protocol_id', '')}",
  subject: "{meta.get('protocol_subject', '')}",
  scenario: "{meta.get('scenario', '')}",
  sop: "{meta.get('sop_number', '')}",
  age: "{meta.get('age_group', '')}",
  version: "{meta.get('version', '')}",
  source: "{meta.get('source_authority', '')}",
  generation_date: "{meta.get('generation_date', '')}",
))
"""


def build_combined_typ(age_groups: list[tuple[str, Path]], output_name: str) -> Path:
    """Build a combined .typ file from protocol directories.

    age_groups: list of (label, directory) pairs, e.g. [("ADULT", adult_dir)]
    """
    protocols = []
    for label, typ_dir in age_groups:
        if not typ_dir.exists():
            print(f"Warning: {typ_dir} does not exist, skipping")
            continue
        for f in sorted(typ_dir.glob("*.typ")):
            text = f.read_text()
            meta = extract_metadata(text)
            content = extract_content(text)
            if content.strip():
                protocols.append((meta, content, f.name))

    # Sort by age group then SOP number
    def sort_key(p):
        meta = p[0]
        age = 0 if meta.get("age_group", "") == "ADULT" else 1
        sop = meta.get("sop_number", "999")
        return (age, sop)

    protocols.sort(key=sort_key)

    out_path = COMBINED_DIR / f"{output_name}.typ"
    with open(out_path, "w") as f:
        f.write(PREAMBLE)

        first = True
        for meta, content, filename in protocols:
            age = meta.get("age_group", "ADULT")
            subject = meta.get("protocol_subject", "")
            sop = meta.get("sop_number", "")

            f.write(f"\n// {'=' * 60}\n")
            f.write(f"// {age} — {subject} (SOP {sop}) [{filename}]\n")
            f.write(f"// {'=' * 60}\n")

            # For the very first protocol, don't emit a pagebreak
            # (the preamble doesn't end with content on a page)
            if first:
                # Write state update without pagebreak
                f.write(f"""
#current-protocol.update((
  id: "{meta.get('protocol_id', '')}",
  subject: "{meta.get('protocol_subject', '')}",
  scenario: "{meta.get('scenario', '')}",
  sop: "{meta.get('sop_number', '')}",
  age: "{meta.get('age_group', '')}",
  version: "{meta.get('version', '')}",
  source: "{meta.get('source_authority', '')}",
  generation_date: "{meta.get('generation_date', '')}",
))
""")
                first = False
            else:
                f.write(state_update(meta))

            f.write(content)
            f.write("\n")

    print(f"Generated: {out_path}")
    return out_path


def compile_typ(typ_path: Path):
    """Compile a .typ file to PDF."""
    pdf_path = typ_path.with_suffix(".pdf")
    print(f"Compiling: {typ_path.name} -> {pdf_path.name}")
    result = subprocess.run(
        ["typst", "compile", str(typ_path), str(pdf_path)],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"  ERROR: {result.stderr}")
        return False
    else:
        if result.stderr:
            # Typst warnings
            for line in result.stderr.strip().split("\n")[:10]:
                print(f"  warn: {line}")
        print(f"  OK: {pdf_path}")
        return True


def main():
    do_compile = "--compile" in sys.argv

    # Build adult-only combined
    adult_typ = build_combined_typ(
        [("ADULT", ADULT_DIR)],
        "israel-adult-combined-all-protocols",
    )

    # Build child-only combined
    child_typ = build_combined_typ(
        [("CHILD", CHILD_DIR)],
        "israel-child-combined-all-protocols",
    )

    # Build everything combined
    all_typ = build_combined_typ(
        [("ADULT", ADULT_DIR), ("CHILD", CHILD_DIR)],
        "israel-all-protocols-combined",
    )

    if do_compile:
        for typ_path in [adult_typ, child_typ, all_typ]:
            compile_typ(typ_path)


if __name__ == "__main__":
    main()
